package com.banco.reclamacoes.domain.model;

public enum CategoriaReclamacao {
    ACESSO_CONTA,
    APLICATIVO,
    COBRANCA,
    FRAUDE,
    CARTAO,
    PIX_TRANSFERENCIA,
    CONTA_CORRENTE,
    EMPRESTIMO_FINANCIAMENTO,
    IMOBILIARIO,
    SEGUROS,
    INVESTIMENTOS,
    ATENDIMENTO,
    DOCUMENTOS_ANEXOS,
    DADOS_CADASTRAIS,
    RENEGOCIACAO_DIVIDA,
    CONSORCIO,
    OUVIDORIA_RECLAMACAO_REGULATORIA,
    OUTROS,
}
